[package]
name = "rerename"
version = "0.3.1"
authors = ["Peter Varo <hello@petervaro.com>"]
edition = "2018"
description = "Smart file renaming with regular expressions"

[dependencies]
regex = "1.3"
clap = "2.33"
